#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                   # enable MSBuild parallel builds
  project: Wexflow.vs2015.sln      # path to Visual Studio solution or project
  verbosity: minimal               # MSBuild verbosity level quiet|minimal|normal|detailed
